// F++ Programming Language Types

export interface FPPNode {
  type: 'element' | 'text' | 'attribute' | 'style' | 'comment';
  tagName?: string;
  attributes?: Record<string, string>;
  styles?: Record<string, string>;
  children?: FPPNode[];
  content?: string;
  indent?: number;
  id?: string;
  classes?: string[];
}

export interface FPPElement {
  type: string;
  tagName: string;
  attributes: Record<string, string>;
  styles: Record<string, string>;
  children: FPPElement[];
  content: string;
  indent: number;
  id?: string;
  classes: string[];
  pseudoStyles?: Record<string, Record<string, string>>;
  animations?: FPAnimation[];
  googleFonts?: string[];
}

export interface FPAnimation {
  name: string;
  duration: string;
  keyframes: Record<string, Record<string, string>>;
}

export interface FPPToken {
  type: 'keyword' | 'string' | 'number' | 'symbol' | 'identifier' | 'newline' | 'indent';
  value: string;
  line: number;
  column: number;
}

export interface FPPParseResult {
  success: boolean;
  ast: FPPElement | null;
  errors: FPError[];
  warnings: string[];
}

export interface FPError {
  line: number;
  column: number;
  message: string;
}

export interface FPPCompileResult {
  success: boolean;
  html: string;
  css: string;
  errors: string[];
  googleFonts: string[];
}

// Element mapping from F++ keywords to HTML tags
export const ELEMENT_MAP: Record<string, string> = {
  'page': 'html',
  'document': 'html',
  'head': 'head',
  'body': 'body',
  'title': 'title',
  'meta': 'meta',
  'icon': 'link',
  'style': 'style',
  'script': 'script',
  'heading': 'h1', // default, can be followed by number
  'heading one': 'h1',
  'heading two': 'h2',
  'heading three': 'h3',
  'heading four': 'h4',
  'heading five': 'h5',
  'heading six': 'h6',
  'h1': 'h1',
  'h2': 'h2',
  'h3': 'h3',
  'h4': 'h4',
  'h5': 'h5',
  'h6': 'h6',
  'paragraph': 'p',
  'para': 'p',
  'p': 'p',
  'text': 'span',
  'span': 'span',
  'link': 'a',
  'anchor': 'a',
  'a': 'a',
  'image': 'img',
  'img': 'img',
  'picture': 'img',
  'button': 'button',
  'btn': 'button',
  'input': 'input',
  'text area': 'textarea',
  'textarea': 'textarea',
  'list': 'ul',
  'ordered list': 'ol',
  'unordered list': 'ul',
  'ol': 'ol',
  'ul': 'ul',
  'item': 'li',
  'list item': 'li',
  'li': 'li',
  'container': 'div',
  'div': 'div',
  'box': 'div',
  'section': 'section',
  'header': 'header',
  'footer': 'footer',
  'navigation': 'nav',
  'nav': 'nav',
  'article': 'article',
  'aside': 'aside',
  'main': 'main',
  'sidebar': 'aside',
  'table': 'table',
  'row': 'tr',
  'table row': 'tr',
  'tr': 'tr',
  'cell': 'td',
  'table cell': 'td',
  'td': 'td',
  'header cell': 'th',
  'th': 'th',
  'form': 'form',
  'label': 'label',
  'select': 'select',
  'option': 'option',
  'checkbox': 'input',
  'radio': 'input',
  'dropdown': 'select',
  'video': 'video',
  'audio': 'audio',
  'source': 'source',
  'iframe': 'iframe',
  'embed': 'embed',
  'canvas': 'canvas',
  'svg': 'svg',
  'line break': 'br',
  'br': 'br',
  'break': 'br',
  'horizontal rule': 'hr',
  'hr': 'hr',
  'divider': 'hr',
  'code': 'code',
  'pre': 'pre',
  'blockquote': 'blockquote',
  'quote': 'blockquote',
  'strong': 'strong',
  'bold': 'strong',
  'emphasis': 'em',
  'italic': 'em',
  'em': 'em',
  'underline': 'u',
  'strikethrough': 's',
  'subscript': 'sub',
  'superscript': 'sup',
  'mark': 'mark',
  'small': 'small',
  'deleted': 'del',
  'inserted': 'ins',
  'abbr': 'abbr',
  'address': 'address',
  'cite': 'cite',
  'details': 'details',
  'summary': 'summary',
  'dialog': 'dialog',
  'menu': 'menu',
  'figure': 'figure',
  'figcaption': 'figcaption',
  'caption': 'caption',
  'colgroup': 'colgroup',
  'col': 'col',
  'thead': 'thead',
  'tbody': 'tbody',
  'tfoot': 'tfoot',
  'datalist': 'datalist',
  'output': 'output',
  'progress': 'progress',
  'meter': 'meter',
  'noscript': 'noscript',
  'template': 'template',
  'slot': 'slot',
};

// Attribute mapping from F++ keywords to HTML attributes
export const ATTRIBUTE_MAP: Record<string, string> = {
  'link': 'href',
  'href': 'href',
  'url': 'href',
  'src': 'src',
  'source': 'src',
  'alt': 'alt',
  'id': 'id',
  'class': 'class',
  'type': 'type',
  'name': 'name',
  'value': 'value',
  'placeholder': 'placeholder',
  'required': 'required',
  'disabled': 'disabled',
  'readonly': 'readonly',
  'checked': 'checked',
  'selected': 'selected',
  'multiple': 'multiple',
  'autocomplete': 'autocomplete',
  'autofocus': 'autofocus',
  'min': 'min',
  'max': 'max',
  'step': 'step',
  'pattern': 'pattern',
  'maxlength': 'maxlength',
  'minlength': 'minlength',
  'size': 'size',
  'cols': 'cols',
  'rows': 'rows',
  'wrap': 'wrap',
  'for': 'for',
  'form': 'form',
  'action': 'action',
  'method': 'method',
  'enctype': 'enctype',
  'target': 'target',
  'rel': 'rel',
  'download': 'download',
  'media': 'media',
  'charset': 'charset',
  'content': 'content',
  'http-equiv': 'http-equiv',
  'property': 'property',
  'lang': 'lang',
  'dir': 'dir',
  'tabindex': 'tabindex',
  'accesskey': 'accesskey',
  'title': 'title',
  'role': 'role',
  'aria-label': 'aria-label',
  'aria-labelledby': 'aria-labelledby',
  'aria-describedby': 'aria-describedby',
  'aria-hidden': 'aria-hidden',
  'data': 'data',
  'draggable': 'draggable',
  'hidden': 'hidden',
  'spellcheck': 'spellcheck',
  'translate': 'translate',
  'controls': 'controls',
  'autoplay': 'autoplay',
  'loop': 'loop',
  'muted': 'muted',
  'preload': 'preload',
  'poster': 'poster',
  'playsinline': 'playsinline',
  'crossorigin': 'crossorigin',
  'integrity': 'integrity',
  'async': 'async',
  'defer': 'defer',
  'nonce': 'nonce',
  'rev': 'rev',
  'shape': 'shape',
  'coords': 'coords',
  'usemap': 'usemap',
  'ismap': 'ismap',
  'loading': 'loading',
  'decoding': 'decoding',
  'fetchpriority': 'fetchpriority',
  'referrerpolicy': 'referrerpolicy',
  'sandbox': 'sandbox',
  'allow': 'allow',
  'width': 'width',
  'height': 'height',
};

// Style property mapping
export const STYLE_MAP: Record<string, string> = {
  'color': 'color',
  'background': 'background',
  'background-color': 'background-color',
  'bg': 'background',
  'bgcolor': 'background-color',
  'font': 'font-family',
  'font-family': 'font-family',
  'font-size': 'font-size',
  'size': 'font-size',
  'font-weight': 'font-weight',
  'weight': 'font-weight',
  'bold': 'font-weight',
  'font-style': 'font-style',
  'italic': 'font-style',
  'text-align': 'text-align',
  'align': 'text-align',
  'center': 'text-align',
  'left': 'text-align',
  'right': 'text-align',
  'justify': 'text-align',
  'text-decoration': 'text-decoration',
  'decoration': 'text-decoration',
  'underline': 'text-decoration',
  'line-through': 'text-decoration',
  'text-transform': 'text-transform',
  'transform': 'text-transform',
  'uppercase': 'text-transform',
  'lowercase': 'text-transform',
  'capitalize': 'text-transform',
  'line-height': 'line-height',
  'letter-spacing': 'letter-spacing',
  'spacing': 'letter-spacing',
  'word-spacing': 'word-spacing',
  'white-space': 'white-space',
  'margin': 'margin',
  'm': 'margin',
  'margin-top': 'margin-top',
  'mt': 'margin-top',
  'margin-right': 'margin-right',
  'mr': 'margin-right',
  'margin-bottom': 'margin-bottom',
  'mb': 'margin-bottom',
  'margin-left': 'margin-left',
  'ml': 'margin-left',
  'padding': 'padding',
  'p': 'padding',
  'padding-top': 'padding-top',
  'pt': 'padding-top',
  'padding-right': 'padding-right',
  'pr': 'padding-right',
  'padding-bottom': 'padding-bottom',
  'pb': 'padding-bottom',
  'padding-left': 'padding-left',
  'pl': 'padding-left',
  'border': 'border',
  'border-width': 'border-width',
  'border-style': 'border-style',
  'border-color': 'border-color',
  'border-radius': 'border-radius',
  'rounded': 'border-radius',
  'radius': 'border-radius',
  'outline': 'outline',
  'box-shadow': 'box-shadow',
  'shadow': 'box-shadow',
  'text-shadow': 'text-shadow',
  'opacity': 'opacity',
  'display': 'display',
  'flex': 'display',
  'grid': 'display',
  'block': 'display',
  'inline': 'display',
  'inline-block': 'display',
  'none': 'display',
  'position': 'position',
  'pos': 'position',
  'absolute': 'position',
  'relative': 'position',
  'fixed': 'position',
  'sticky': 'position',
  'static': 'position',
  'top': 'top',
  'right': 'right',
  'bottom': 'bottom',
  'left': 'left',
  'z-index': 'z-index',
  'z': 'z-index',
  'float': 'float',
  'clear': 'clear',
  'overflow': 'overflow',
  'overflow-x': 'overflow-x',
  'overflow-y': 'overflow-y',
  'visible': 'visibility',
  'visibility': 'visibility',
  'cursor': 'cursor',
  'pointer': 'cursor',
  'transition': 'transition',
  'animation': 'animation',
  'transform': 'transform',
  'rotate': 'transform',
  'scale': 'transform',
  'translate': 'transform',
  'skew': 'transform',
  'filter': 'filter',
  'blur': 'filter',
  'brightness': 'filter',
  'contrast': 'filter',
  'grayscale': 'filter',
  'hue-rotate': 'filter',
  'invert': 'filter',
  'opacity-filter': 'filter',
  'saturate': 'filter',
  'sepia': 'filter',
  'backdrop-filter': 'backdrop-filter',
  'mix-blend-mode': 'mix-blend-mode',
  'background-blend-mode': 'background-blend-mode',
  'clip-path': 'clip-path',
  'mask': 'mask',
  'object-fit': 'object-fit',
  'object-position': 'object-position',
  'aspect-ratio': 'aspect-ratio',
  'gap': 'gap',
  'row-gap': 'row-gap',
  'column-gap': 'column-gap',
  'flex-direction': 'flex-direction',
  'direction': 'flex-direction',
  'flex-wrap': 'flex-wrap',
  'wrap': 'flex-wrap',
  'flex-flow': 'flex-flow',
  'justify-content': 'justify-content',
  'justify': 'justify-content',
  'align-items': 'align-items',
  'items': 'align-items',
  'align-content': 'align-content',
  'align-self': 'align-self',
  'order': 'order',
  'flex-grow': 'flex-grow',
  'grow': 'flex-grow',
  'flex-shrink': 'flex-shrink',
  'shrink': 'flex-shrink',
  'flex-basis': 'flex-basis',
  'basis': 'flex-basis',
  'grid-template-columns': 'grid-template-columns',
  'grid-template-rows': 'grid-template-rows',
  'grid-template-areas': 'grid-template-areas',
  'grid-area': 'grid-area',
  'grid-column': 'grid-column',
  'grid-row': 'grid-row',
  'place-items': 'place-items',
  'place-content': 'place-content',
  'columns': 'columns',
  'column-count': 'column-count',
  'column-gap': 'column-gap',
  'column-rule': 'column-rule',
  'break-after': 'break-after',
  'break-before': 'break-before',
  'break-inside': 'break-inside',
  'page-break-after': 'page-break-after',
  'page-break-before': 'page-break-before',
  'page-break-inside': 'page-break-inside',
  'list-style': 'list-style',
  'list-style-type': 'list-style-type',
  'list-style-position': 'list-style-position',
  'list-style-image': 'list-style-image',
  'table-layout': 'table-layout',
  'border-collapse': 'border-collapse',
  'border-spacing': 'border-spacing',
  'empty-cells': 'empty-cells',
  'caption-side': 'caption-side',
  'content': 'content',
  'quotes': 'quotes',
  'counter-reset': 'counter-reset',
  'counter-increment': 'counter-increment',
  'resize': 'resize',
  'user-select': 'user-select',
  'pointer-events': 'pointer-events',
  'touch-action': 'touch-action',
  'scroll-behavior': 'scroll-behavior',
  'scroll-snap-type': 'scroll-snap-type',
  'scroll-snap-align': 'scroll-snap-align',
  'overscroll-behavior': 'overscroll-behavior',
  'perspective': 'perspective',
  'perspective-origin': 'perspective-origin',
  'transform-origin': 'transform-origin',
  'transform-style': 'transform-style',
  'backface-visibility': 'backface-visibility',
  'isolation': 'isolation',
  'all': 'all',
  'appearance': 'appearance',
  'accent-color': 'accent-color',
  'caret-color': 'caret-color',
  'color-scheme': 'color-scheme',
  'hyphens': 'hyphens',
  'line-break': 'line-break',
  'overflow-wrap': 'overflow-wrap',
  'tab-size': 'tab-size',
  'text-indent': 'text-indent',
  'text-justify': 'text-justify',
  'text-orientation': 'text-orientation',
  'text-overflow': 'text-overflow',
  'text-rendering': 'text-rendering',
  'unicode-bidi': 'unicode-bidi',
  'writing-mode': 'writing-mode',
  'word-break': 'word-break',
  'word-wrap': 'word-wrap',
  'fill': 'fill',
  'stroke': 'stroke',
  'stroke-width': 'stroke-width',
  'stroke-dasharray': 'stroke-dasharray',
  'stroke-dashoffset': 'stroke-dashoffset',
  'stroke-linecap': 'stroke-linecap',
  'stroke-linejoin': 'stroke-linejoin',
  'stroke-miterlimit': 'stroke-miterlimit',
};

// Color name to hex mapping
export const COLOR_MAP: Record<string, string> = {
  'red': '#ff0000',
  'green': '#00ff00',
  'blue': '#0000ff',
  'yellow': '#ffff00',
  'cyan': '#00ffff',
  'magenta': '#ff00ff',
  'white': '#ffffff',
  'black': '#000000',
  'orange': '#ffa500',
  'pink': '#ffc0cb',
  'purple': '#800080',
  'brown': '#a52a2a',
  'gray': '#808080',
  'grey': '#808080',
  'silver': '#c0c0c0',
  'gold': '#ffd700',
  'navy': '#000080',
  'teal': '#008080',
  'olive': '#808000',
  'maroon': '#800000',
  'aqua': '#00ffff',
  'lime': '#00ff00',
  'fuchsia': '#ff00ff',
  'coral': '#ff7f50',
  'salmon': '#fa8072',
  'crimson': '#dc143c',
  'tomato': '#ff6347',
  'indigo': '#4b0082',
  'violet': '#ee82ee',
  'plum': '#dda0dd',
  'lavender': '#e6e6fa',
  'beige': '#f5f5dc',
  'ivory': '#fffff0',
  'khaki': '#f0e68c',
  'tan': '#d2b48c',
  'sienna': '#a0522d',
  'chocolate': '#d2691e',
  'peru': '#cd853f',
  'sandy': '#f4a460',
  'wheat': '#f5deb3',
  'linen': '#faf0e6',
  'azure': '#f0ffff',
  'mint': '#f5fffa',
  'snow': '#fffafa',
  'seashell': '#fff5ee',
  'floralwhite': '#fffaf0',
  'ghostwhite': '#f8f8ff',
  'honeydew': '#f0fff0',
  'whitesmoke': '#f5f5f5',
  'gainsboro': '#dcdcdc',
  'lightgray': '#d3d3d3',
  'lightgrey': '#d3d3d3',
  'darkgray': '#a9a9a9',
  'darkgrey': '#a9a9a9',
  'dimgray': '#696969',
  'dimgrey': '#696969',
  'slategray': '#708090',
  'slategrey': '#708090',
  'lightslategray': '#778899',
  'lightslategrey': '#778899',
  'darkslategray': '#2f4f4f',
  'darkslategrey': '#2f4f4f',
  'lightblue': '#add8e6',
  'lightcoral': '#f08080',
  'lightcyan': '#e0ffff',
  'lightgoldenrodyellow': '#fafad2',
  'lightgreen': '#90ee90',
  'lightpink': '#ffb6c1',
  'lightsalmon': '#ffa07a',
  'lightseagreen': '#20b2aa',
  'lightskyblue': '#87cefa',
  'lightslategray': '#778899',
  'lightsteelblue': '#b0c4de',
  'lightyellow': '#ffffe0',
  'darkblue': '#00008b',
  'darkcyan': '#008b8b',
  'darkgoldenrod': '#b8860b',
  'darkgray': '#a9a9a9',
  'darkgreen': '#006400',
  'darkgrey': '#a9a9a9',
  'darkkhaki': '#bdb76b',
  'darkmagenta': '#8b008b',
  'darkolivegreen': '#556b2f',
  'darkorange': '#ff8c00',
  'darkorchid': '#9932cc',
  'darkred': '#8b0000',
  'darksalmon': '#e9967a',
  'darkseagreen': '#8fbc8f',
  'darkslateblue': '#483d8b',
  'darkslategray': '#2f4f4f',
  'darkslategrey': '#2f4f4f',
  'darkturquoise': '#00ced1',
  'darkviolet': '#9400d3',
  'deepskyblue': '#00bfff',
  'dodgerblue': '#1e90ff',
  'firebrick': '#b22222',
  'forestgreen': '#228b22',
  'goldenrod': '#daa520',
  'greenyellow': '#adff2f',
  'hotpink': '#ff69b4',
  'indianred': '#cd5c5c',
  'lawngreen': '#7cfc00',
  'lemonchiffon': '#fffacd',
  'lightpink': '#ffb6c1',
  'midnightblue': '#191970',
  'mediumaquamarine': '#66cdaa',
  'mediumblue': '#0000cd',
  'mediumorchid': '#ba55d3',
  'mediumpurple': '#9370db',
  'mediumseagreen': '#3cb371',
  'mediumslateblue': '#7b68ee',
  'mediumspringgreen': '#00fa9a',
  'mediumturquoise': '#48d1cc',
  'mediumvioletred': '#c71585',
  'orange': '#ffa500',
  'orangered': '#ff4500',
  'orchid': '#da70d6',
  'palegoldenrod': '#eee8aa',
  'palegreen': '#98fb98',
  'paleturquoise': '#afeeee',
  'palevioletred': '#db7093',
  'papayawhip': '#ffefd5',
  'peachpuff': '#ffdab9',
  'powderblue': '#b0e0e6',
  'rosybrown': '#bc8f8f',
  'royalblue': '#4169e1',
  'saddlebrown': '#8b4513',
  'skyblue': '#87ceeb',
  'slateblue': '#6a5acd',
  'springgreen': '#00ff7f',
  'steelblue': '#4682b4',
  'turquoise': '#40e0d0',
  'yellowgreen': '#9acd32',
};
